version: 2

aliases:
  - working_directory: &working_directory ~/homieiot.ts
  - image: &image circleci/node:lts
  - &defaults
    working_directory: *working_directory
    docker:
      - image: *image
  - &step_attach_workspace
    attach_workspace:
      at: *working_directory

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - *step_attach_workspace
      - run:
          name: 'Install Dependencies'
          command: 'yarn install'
      - persist_to_workspace:
          root: .
          paths: .
  build:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - run:
          name: build
          command: 'yarn build'
      - persist_to_workspace:
          root: .
          paths: dist
  release:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - run:
          name: release
          command: 'yarn semantic-release || true'
  test:
    working_directory: *working_directory
    docker:
      - image: *image
      - image: eclipse-mosquitto:latest
        ports:
          - '1883:1883'
    steps:
      - *step_attach_workspace
      - run:
          name: Test
          command: 'yarn jest --ci --passWithNoTests --coverage'
      - run:
          name: Codecov
          command: 'yarn codecov'
  lint:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - run:
          name: Lint
          command: 'yarn lint'
  docs:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - run:
          name: Add github ssh keys
          command: mkdir ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Configure git email
          command: git config --global user.email "hola@alejandroherr.io"
      - run:
          name: Configure git name
          command: git config --global user.name "AlejandroHerr"
      - run:
          name: Generate docs
          command: yarn docs
      - run:
          name: Commit
          command: 'git add ./docs && git commit -m "docs: update docs [skip ci]" && git push --set-upstream origin $(git branch | grep \* | cut -d " " -f2)'
      - persist_to_workspace:
          root: .
          paths: .

workflows:
  version: 2
  main_flow:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - docs:
          requires:
            - checkout
      - release:
          requires:
            - build
            - test
            - lint
            - docs
