version: 2
jobs:
  install:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: yarn install
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install
      - run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
