version: "3.4"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
  node_app:
    image: node:lts
    depends_on:
      - mosquitto
    environment:
      - NODE_ENV=testing
      - MQTT_PORT=1883
      - MQTT_PROTOCOL=mqtt
      - MQTT_HOST=mosquitto
    stdin_open: true
    tty: true
    working_dir: /homie
    volumes:
      - "node_modules:/homie/node_modules"
      - "../.git:/homie/.git"
      - "../coverage:/homie/coverage"
      - "../docker/scripts:/homie/docker/scripts"
      - "../src:/homie/src"
      - "../.gitignore:/homie/.gitignore"
      - "../jest.config.js:/homie/jest.config.js"
      - "../package.json:/homie/package.json"
      - "../tsconfig.json:/homie/tsconfig.json"
      - "../yarn.lock:/homie/yarn.lock"
    entrypoint: ["/bin/sh"]

volumes:
  node_modules:
